strategy("볼린저밴드 + 필터링 전략", overlay=true, fill_orders_on_standard_ohlc = true, process_orders_on_close = true, margin_long = 0, margin_short = 0)

bb_length = input.int(20, "기간") //메뉴에 기간 입력창을 정수 기반으로 생성하기 위해 변수명을 정의하는 코드이다.
bb_multi = input.float(2, "표준편차", step = 0.1) //마찬가지로 표준편차 입력창을 실수 기반으로 생성함. * 토글로 증감 조절하려면 step = 0.1 추가함.
[middle, upper, lower] = ta.bb(close, bb_length, bb_multi)
plot(middle, color=color.yellow)
u = plot(upper, color=color.yellow)
l = plot(lower, color=color.yellow)

fill(u, l, color = color.new(color.yellow, 90))

is_long = ta.crossunder(low, lower)
if is_long
    strategy.entry("롱", strategy.long)

is_long_close = ta.crossover(high, upper)
if is_long_close
    strategy.close("롱")
